### ISSUE TITLE
Clean up the product page 

### ISSUE THREAD

**Issue by drupalsunil** [Rakolkata/medshop#29]
Remove Stock, mrp, exp date, strip and batch no form product add/edit page, _it should move to product varient( already done)_

**Comment by rakol-nikhil** [comment]
completed

**Comment by drupalsunil** [comment]
save not working
<img width="872" alt="image" src="https://github.com/Rakolkata/medshop/assets/27809668/1f0bd9c9-9113-4966-aa1a-146cf53759e7">
